### ISSUE TITLE
support HBEFA cold emissions

### ISSUE THREAD

**Issue by twollnik** [twollnik/YETI#1]
Implement `HbefaColdStrategy` to calculate cold start emissions with the HBEFA methodology. 

HBEFA cold emissions are based on 
- The number of starts per vehicle at each street link
- A fixed emissions value per vehicle and start in grams

This leads to the following **formula**:
```python
cold_emissions_for_link_a_and_vehicle_a = \
    number_of_starts_for_vehicle_a_at_link_a * cold_emissions_per_start_for_vehicle_a
```

**Input data** will be in the same format as traffic input data for HBEFA hot emissions (excluding the los columns):

LinkID | Dir | DayType | Hour | NumberOfStarts
--- | --- | --- | --- | --- 

We will use the fleet composition and the vehicle category percentages to divide the `NumberOfStarts` between the different vehicle types.

**Checklist**

- [x] Add load_input_data_function (incl. tests)
- [x] Add load_unified_data_function (incl. tests)
- [x] Add HbefaColdStrategy (incl. tests)
- [ ] Add validation_function (TODO for Tom)
- [x] Add example data and example config (incl. tests)
- [ ] Add docs page "HbefaColdStrategy" (TODO for Joana)

**Comment by twollnik** [comment]
@JoanaLeitao
In #25 we were talking about combining different hot and cold strategies. But the HBEFA cold emissions don't depend on any hot emissions.

Do you think it still makes sense to merge HbefaColdStrategy and HbefaHotStrategy into one HbefaStrategy? (even if the two strategies are completely independent?)

**Comment by JoanaLeitao** [comment]
There should be a "strategy" that calculates hot&cold together or at least provides that option - it's not about depending on each other but rather the fact of avoiding have to start the run twice if in any case the user wants both.
As Tim said, no cold it's "incomplete" calculation - although hot already provides the great part of emissions but they would be underestimated without the cold
so they don't need to be "together" but there would be a possibility of calculating one after the other

**Comment by twollnik** [comment]
Okay I see. Thanks for the clarification.

**Comment by twollnik** [comment]
@JoanaLeitao The `HbefaColdStrategy` is implemented. There are three things still missing:
1. A docs page for the new Strategy
2. A validation function for mode input_data
3. A validation function for mode unified_data

If I remember correctly you wanted to do the docs page. Do you also want to add the validation functions or should I do that?
