### ISSUE TITLE
Add fixed ef Strategy

### ISSUE THREAD

**Issue by twollnik** [twollnik/YETI#2]
Implement a Strategy to work with fixed ef for each vehicle.

**Comment by twollnik** [comment]
@JoanaLeitao

The way I see it this Strategy duplicates the logic of `HbefaColdStrategy` (See #1). `HbefaColdStrategy` also uses fixed "emission factors" for each vehicle and pollutant.  The formula to calculate hbefa cold emissions is this:
```python
cold_emissions_for_link_a_and_vehicle_a = \
    number_of_starts_for_vehicle_a_at_link_a * cold_emissions_per_start_for_vehicle_a
```

The factor `cold_emissions_per_start_for_vehicle_a` could also be interpreted as a fixed emission factor for the vehicle "vehicle_a".

So, in my opinion we can use the `FixedEfStrategy` to calculate hbefa hot emissions. Do you understand what I mean and am I right?

In light of this discovery I suggest to use our coding session tomorrow to implement the `FixedEfStrategy` rather than the `HbefaColdStrategy`. Do you agree?

**Comment by JoanaLeitao** [comment]
... updated below
....
I'm sorry but I don't really understand exactly what you mean.
It is similar yes to the hot emissions calculation ... still different... and I can't see the similarity to the cold.
I guess then we need to make also clear what exactly should be done with "Fixed EF" ...

**Comment by twollnik** [comment]
@JoanaLeitao Allow me to clarify.

The `HbefaColdStrategy` uses data such as:

_cold_emissions_per_start.csv_

VehName | EmissionsPerStart
--- | ---
vehicle a | 1.5
...

_traffic_data.csv_

LinkID | DayType | Hour | Dir | VehCount
-- | --- | --- | --- | ---
link a | 2 | 15 | 0 | 100

It also uses link data and fleet composition data.

The Strategy will then find out how much of the traffic at each link can be attributed to each vehicle. Then it multiplies the result with the EmissionsPerStart for the vehicle.

The `FixedEfStrategy` uses very similar data. The one difference is that instead of cold_emissions_per_start.csv it uses _emission_factors.csv_:

VehName | EF
--- | ---
vehicle a | 1.5

The `FixedEfStrategy` will now operate much like the `HbefaColdStrategy`. Just instead of multiplying with EmissionsPerStart it will multiply with EF. So the only difference between the two Strategies is the name of the second column in the emissions factor dataset.

Does this make it more clear?

**Comment by JoanaLeitao** [comment]
@twollnik 

So looking at it you are partly right. 
I've been trying to think of several situations and maybe at this point there's a way of optimizing implementation but not like you are saying.

By fixed EF we sort of mean a "prescribed/forced" EF, and this is what is done in HBEFA - we use per TrafficSit per Veh an EF that we extracted from HBEFA but the user can simply decide whatever values (s)he wants. 
The calculation of hot emissions between COPERT and HBEFA is different only by the fact that EF in COPERT are determined by coefficients for an equation while in HBEFA they are prescribed with values per TrafficSit/VehCat. 
So maybe we should just change the names to something that general and if the user wants to prescribe EF a file like currently is used for HBEFA is to created.  

This would work if user provides for every single traffic sit/veh cat in the input data an EF, right?

If I understood you correctly I don't think the cold calculation is correct. 
The cold emissions calculation should not multiply the emission excess factor by the traffic at each link (that is already flowing) but rather only the number of starts per veh cat per (or at each) link. This is a number we do not have yet.

**Comment by twollnik** [comment]
@JoanaLeitao 

It's the `HbefaHotStrategy`, sorry about that. I had `HbefaHotStrategy` in an earlier version, but then mistakenly changed it to `HbefaColdStrategy`. Now it should all make sense.
The `HbefaHotStrategy` and the `FixedEfStrategy` basically do the same thing. Would you agree?

And yes, you are right that the `HbefaHotStrategy` uses starts and not vehicle counts, hovewer the processing is much the same.

**Comment by twollnik** [comment]
@JoanaLeitao
> By fixed EF we sort of mean a "prescribed/forced" EF, and this is what is done in HBEFA - we use per TrafficSit per Veh an EF that we extracted from HBEFA but the user can simply decide whatever values (s)he wants.

Wouldn't this mean that the `FixedEfStrategy` and the `HbefaHotStrategy` do exactly the same thing? If so, I agree that we should just change the name to something general. Also there would not be a need to create a new `FixedEfStrategy` anymore.

I thought that the `FixedEfStrategy` should work with a fixed ef per vehicle. The ef would not be dependent on the traffic situation. I guess my understanding was incorrect?

-------

> If I understood you correctly I don't think the cold calculation is correct.
The cold emissions calculation should not multiply the emission excess factor by the traffic at each link (that is already flowing) but rather only the number of starts per veh cat per (or at each) link. This is a number we do not have yet.

Yes, you are right. I overlooked this detail because the processing is much the same.

**Comment by twollnik** [comment]
**Conclusion**

The `HbefaHotStrategy` and the `FixedEfStrategy` do the same thing. There is no need to add a seperate `FixedEfStrategy`. We might rename the `HbefaHotStrategy` to `FixedEfStrategy` in the future.
